# typed: false
# frozen_string_literal: true

# Generated by packages/kodine/script/publish.ts. DO NOT EDIT.
class Kodine < Formula
  desc "AI coding agent that lives in your terminal."
  homepage "https://kodine.net"
  version "1.0.12"

  depends_on "ripgrep"

  on_macos do
    if Hardware::CPU.intel?
      url "https://kodine.net/downloads/cli/1.0.12/kodine-darwin-x64.zip"
      sha256 "b8ab87d6bd437fff26e7219a6e85e9197e97530988749249ed60dd8fa5667ff8"

      def install
        bin.install "kodine"
      end
    end
    if Hardware::CPU.arm?
      url "https://kodine.net/downloads/cli/1.0.12/kodine-darwin-arm64.zip"
      sha256 "2ce3d01e18f2c3ee10ff19439b4fadc73f8f8e3fb757609ce9312752444aaae3"

      def install
        bin.install "kodine"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://kodine.net/downloads/cli/1.0.12/kodine-linux-x64.tar.gz"
      sha256 "c866b730141499bde31b8d16e54f1a07577209d722359ae6502722e40e9c97aa"
      def install
        bin.install "kodine"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://kodine.net/downloads/cli/1.0.12/kodine-linux-arm64.tar.gz"
      sha256 "de52b7f5cc8bfe9df1a5b30075576219ff00ea456e464caad00c8527c8d3a21d"
      def install
        bin.install "kodine"
      end
    end
  end
end

