# typed: false
# frozen_string_literal: true

# Generated by packages/kodine/script/publish.ts. DO NOT EDIT.
class Kodine < Formula
  desc "AI coding agent that lives in your terminal."
  homepage "https://github.com/kodine-ai/kodine"
  version "1.0.10"

  depends_on "ripgrep"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kodine-ai/kodine/releases/download/v1.0.10/kodine-darwin-x64.zip"
      sha256 "bccf5a29adf3d6648b0246b167d7a157f6219986dfec7dae9e67ac4368da51f0"

      def install
        bin.install "kodine"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kodine-ai/kodine/releases/download/v1.0.10/kodine-darwin-arm64.zip"
      sha256 "39b694038369d383e14e127c7a87388790c73b28b7fa8d476033eb9ef08eee06"

      def install
        bin.install "kodine"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/kodine-ai/kodine/releases/download/v1.0.10/kodine-linux-x64.tar.gz"
      sha256 "6ff4e53f437a8983f08a438f2850feb6d03b8fb6e87777ad2b9e2d8979923e5b"
      def install
        bin.install "kodine"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/kodine-ai/kodine/releases/download/v1.0.10/kodine-linux-arm64.tar.gz"
      sha256 "0aecd03510ed5d922405aac0c4453ea76e64319eca6102b72f88cc46095506ae"
      def install
        bin.install "kodine"
      end
    end
  end
end

